# The URL the site will be built for
base_url = "https://huia.zwitterio.it"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Built in taxonomies of huia.
taxonomies = [
           {name = "tags"},
           {name = "categories"},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# The max-width of the page content
grid_size = "grid-sm"

# Default author for articles
author = "You"

# Menu items to display. You define a url and the name of the menu item.
# NOTE: `$BASE_URL/` must be included in the url name.
main_menu = [
              {url="/about/", name="about"},
              {url="/contact/", name="contact"},
]

# Post metadata
show_author = true
show_tags = true
show_categories = true
read_more = "read more"

[extra.sidebar]
active=true
# text_snippet="Some text here"
tweets=true
popular_tags=false
archive=false
syndicate=false
