# The URL the site will be built for
base_url = "/"

title = "iRay"
description = "Another Zola theme, this time written with Spectre."

# 是否自动生成RSS提要
generate_feed = false
feed_filename = "rss.xml"

# 是否自动编译Sass目录中的所有Sass文件
compile_sass = true

# 是否构建搜索索引供JavaScript库稍后使用
build_search_index = false

# 内置taxonomies.
taxonomies = [
           {name = "tags"},
           {name = "categories"},
]

[markdown]
# 是否进行语法突出显示
# 主题可以通过`highlight_theme` 变量设置为Zola支持的主题
highlight_code = true

[extra]
# 页面最大宽度(max-width )设置
grid_size = "grid-lg"

# 文章默认作者
author = "iRay"
# 文章概览是否展示作者
show_author = false
# 文章概览是否展示标签
show_tags = false
# 文章概览是否展示分类
show_categories = true
# 阅读全文按钮名称设置
read_more_prompt = "阅读全文"
# 发布设置(展示地方没看到)
read_post_prompt = "read post"

# Menu 夹层菜单,手机或者细长浏览时候菜单是否隐藏
hamburger_menu = false

# 要显示的菜单项。可以定义一个url和菜单项的名称.
# NOTE: `$BASE_URL/` must be included in the url name.
main_menu = [
              {url="/tags/", name="标签"},
              {url="/categories/", name="分类"},
              {url="/about", name="关于"},
]

# Footer
# 网页下方可设置标语，可释放注释
#footer_tagline = "Your tagline"

## 网页下方社交链接，可解放注释
# social_links = [
#     {url = "https://t.me/", name = "telegram"},
#     {url = "https://twitter.com/", name = "twitter"},
#     {url = "https://github.com/", name = "github"},
#     # {url = "", name = "instagram"},
#     # {url = "", name = "facebook"},
# ]


[extra.sidebar]
# Enable/Disable sidebar
# 是否有边栏，注释或者false会报错
active=true

# Include a text snippet in the sidebar
# 侧栏标语，可放文字或者HTML格式内容
text_snippet="Some <strong>HTML</strong> here! It's <mark>safe</mark>!"

# 名片说明，一句话介绍自己
author_bio = "Don't Be Same Be Better !"
# 头像
author_avatar = "avatar.png"

# Include search bar
# 索引功能还未上线？
# TODO template

# Embed twitter iframe in the sidebar
# tweets_by="gicrisf"

# TODO
popular_tags=false
archive=false
related_posts=false
